fix: remove flex capability in .post-meta div element to allow tag-list line breaks
vaga/hugo-theme-m10c pull request #115
Opened 2023-11-15 12:23 UTC by flo-kn

Closes: #114

Hi there 👋,
removing the `flex` capability form `.post-meta` fixes issue #114 for me. 
Please have a look if the suggested change does not break anything that I might not have been aware of!

Here a demo with the [exampleSite](https://github.com/vaga/hugo-theme-m10c/tree/master/exampleSite):

![tag-list-line-break-video](https://github.com/vaga/hugo-theme-m10c/assets/104433967/031d84c4-b830-4f36-93c4-95ff292e2139)

2023-11-18 13:29 UTC, vaga commented
Hi,
`display: flex;` is used to center vertically icons with texts.

Try this: 
```scss
.post-meta > div {
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: 0.2em;
  font-size: 0.8em;

  > .icon {
    margin-right: 0.4em;
  }
}
```

I added `flex-wrap: wrap;` to fix the issue and added `gap: 0.2em;` to space tags.
You can update the PR if it works for you. :)
Thanks,

2023-11-18 13:29 UTC, vaga requested changes
Hi,
`display: flex;` is used to center icons vertically with text.

Try this: 
```scss
.post-meta > div {
  display: flex;
  align-items: center;
  flex-wrap: wrap;
  gap: 0.2em;
  font-size: 0.8em;

  > .icon {
    margin-right: 0.4em;
  }
}
```

I added `flex-wrap: wrap;` to fix the issue and added `gap: 0.2em;` to space tags.
You can update the PR if it works for you. :)
Thanks,

2023-11-19 17:34 UTC, flo-kn commented
> You can update the PR if it works for you. :)

Works perfectly. Thanks.

2023-11-21 02:30 UTC, vaga approved these changes

2023-11-21 02:30 UTC, merged